only_gitlab_yml:
  script: env
  only:
    changes:
    - .gitlab-ci.yml

only_readme:
  script: env
  only:
    changes:
    - README.md
    
on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests

only_gitlab_yml_epr:
  stage: test
  script: env
  only:
    - external_pull_requests
    changes:
      - .gitlab-ci.yml

only_readme_epr:
  stage: test
  script: env
  only:
    - external_pull_requests
    changes:
      - README.md

only_external_pull_requests:
  stage: test
  script: env
  only:
    - external_pull_requests
